name: Get Sentiment and update GitHub page
    
jobs:
  refresh_page:
    runs-on: ubuntu-latest
    
    steps:
      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script to update sentiment page
        run: python update_sentiment_page.py
        
      - name: Clone repo from your github.io page and commit newly generated sentiment html file
        run: | 
          git clone https://github.com/SaloniJhalani/SaloniJhalani.github.io.git/ 
          cp live_sentiment.html SaloniJhalani.github.io/live_sentiment.html 
          cd SaloniJhalani.github.io 
          git add live_sentiment.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh stock sentiment page'        
        
      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.TOKEN }}          
          repository: "SaloniJhalani/SaloniJhalani.github.io"
          branch: "main"
          directory: ./SaloniJhalani.github.io
